module ElasticGraph
  module Protobuf
    module SchemaDefinition
      module ObjectInterfaceAndUnionExtension : ::ElasticGraph::SchemaDefinition::SchemaElements::anyObjectType
        def to_proto_field_type: () -> ::String
      end
    end
  end
end
